### ISSUE TITLE
tuning alignment soft-clipping for variant recall

### ISSUE THREAD

**Issue by mdkeehan** [RWilton/Arioc#11]
![arioc-softclipping4](https://user-images.githubusercontent.com/21029749/102025060-645f0800-3dfa-11eb-910a-414bda6b776d.png)
I have noticed that Arioc produces slightly more soft clips in the alignments than an alternative (bwa mem).
The IGV screenshot shows an example from the Arioc test data.  BWA alignment in the centre: two reads carry the alternative alignment A.
Arioc at the bottom soft clips resulting in a single A and a soft clip.
My untuned simple test bcftools variant calling pipeline then produces an A variant call from BWA but not from Arioc.

Overall I have noticed that Arioc alignments result in precise variant calls (in very high agreement to BWA alignment variant calls) but that BWA alignments will generate more lower quality snps in a subsequent variant calling stage. This is likely caused by the default settings for bcftools variant calling being compatible with BWA. I attribute many of these to the MAPQ differences. However my users would be concerned by the lower recall.

1. The Arioc papers mention that the non gapped aligner will produce soft clips under certain conditions. Is there a user controllable parameter to tune soft clipping?

2. Suggestions on using arioc as a drop in replacement aligner for a variant calling pipeline in either a high-precision or a high-recall variant calling setting might be helpful to users.

**Comment by RWilton** [comment]
Can you please verify that you are using both Arioc and BWA with the same alignment scoring parameters?  Your screen snap shows an AS (alignment score) of 196 for the mapping reported by Arioc versus 98 for BWA's mapping.  Unless you use the same scoring parameters, it is hard to make any head-to-head comparison of specific read mappings by two different aligners.

I am very much interested in the differences between Arioc and BWA in terms of variant calling, in particular because Arioc's model for MAPQ computation differs from that of BWA-MEM.  But that's  somewhat tangential to the question of soft clipping -- could we continue that discussion offline?

**Comment by mdkeehan** [comment]
Hi Richard,

Happy to continue discussing the differences in the variant calling
offline.

Mike
