### ISSUE TITLE
Issue while running AriocU and AriocP

### ISSUE THREAD

**Issue by xerien** [RWilton/Arioc#2]
When I tried to use AriocU for alignment, I got this error:

```
48:57.530 [00001277] ApplicationException ([0x4727] CppCommon/RaiiDirectory.cpp 321): GetFilenames: scandir failed (errno=2)

```

Strange, since AriocE binaries are working fine, and I have double checked the paths.

**Comment by RWilton** [comment]
Sure is strange -- assuming the file specification (path+filename) in the .cfg file correctly identifies the .sbf file(s) that AriocE created.  The error is coming from a call to the file-open API, so it's hard to see where the function call is contaminated.

If you still haven't figured it out, don't hesitate to send me a copy of the .cfg file you are using.  Perhaps I will see something...
- rw

**Comment by xerien** [comment]
Well, the error which you received is not exactly the one that occurred, the initial one was due to badly places path. Error: 

```
48:57.530 [00001277] ApplicationException ([0x4727] CppCommon/RaiiDirectory.cpp 321): GetFilenames: scandir failed (errno=2)
```

This is the .cfg file

```
<?xml version="1.0" encoding="utf-8"?>

<AriocU gpuMask="0x00000001" batchSize="128k">

  <R>/data/Arioctest/hg19</R>

  <nongapped seed="ssi84_2_30" />

  <gapped seed="hsi20_0_30" Wmxgs="2,6,5,3" Vt="L,100,0" />

  <Q filePath="/data/Arioctest/hg19read">
    <unpaired referenceId="1">
      <file>i250p_1</file>
    </unpaired>
  </Q>

  <A overwrite="true">
    <sam report="mu">/data/Arioctest/result</sam>
  </A>

</AriocU>
```

**Comment by RWilton** [comment]
Sorry, I cannot tell from your message whether you found the problem or whether the problem persists.  If you are still having the problem, then I really don't see how to reproduce it from what you have told me, so please help me out with a bit more information.

The .cfg file looks ok to me.

The call to the system API function scandir() uses paths that are either specified in or derived from the paths in the .cfg file.  If that API is failing, then it's hard to tell from here what's wrong with the path specification(s).  I suppose it's possible that it's a problem with upper/lower case or with having a trailing separator on the path specification (e.g., /data/Arioctest/hg19/ instead of /data/Arioctest/hg19), so you might double-check that.

In any event, if you fix the problem, would you mind letting me know how you fixed it so I can code around it?
- rw

**Comment by xerien** [comment]
Well, I have checked all the parameters in configuration file. And yeah, the problem persists(I am still trying to find a solution). 
Also, I am using absolute paths anyway, and since the same function is working with AriocU, it is kind of perplexing for me too.  Ah, I should tell you that I am using pre compiled binaries. 

Another thing, I don't think that Arioc supports multiple GPU ? We are currently using three nvidia Titan X along with a Tesla K40c, so it might be interesting to see the performance statistics. BARRACUDA does work well after using their supplied script for data fragmentation.

**Comment by RWilton** [comment]
Well, that is strange.  I certainly want to know how you resolve the problem.  If you can come up with a way for me to reproduce the problem, I will be glad to troubleshoot it at this end.

To use multiple GPUs, specify the gpuMask parameter in the AriocU or AriocP element of the .cfg file.  Bit 0 uses GPU device 0, bit 1 uses GPU device 1, and so on:
    gpuMask="0x00000007"
- rw

**Comment by RWilton** [comment]
One other possibility:  since you are using the precompiled binaries, perhaps I can do a build for you that puts some scaffolding around the call to scandir() so we can see exactly what it thinks it's doing.  This week is kind of busy for me, however, so it would have to wait until next week...
- rw

From: Richard Wilton [mailto:richard.wilton@jhu.edu]
Sent: Thursday, June 25, 2015 13:26
To: RWilton/Arioc; RWilton/Arioc
Cc: RWilton
Subject: RE: [Arioc] Issue while running AriocU and AriocP (#2)

Well, that is strange.  I certainly want to know how you resolve the problem.  If you can come up with a way for me to reproduce the problem, I will be glad to troubleshoot it at this end.

To use multiple GPUs, specify the gpuMask parameter in the AriocU or AriocP element of the .cfg file.  Bit 0 uses GPU device 0, bit 1 uses GPU device 1, and so on:
    gpuMask="0x00000007"
- rw

**Comment by xerien** [comment]
Agh, I'm waiting for that build. Still unable to do the task, after reinstalling the OS.

**Comment by xerien** [comment]
Nevermind, the error is now resolved. (I don't know why, but it's resolved, I removed the try/catch exception instance in your code, but that is probably not the wisest thing to do.)
Now I'm having two different "random" errors again, and I'm working with the given sample data.
"terminate called after throwing an instance of 'ApplicationException*' "
and (sometimes)
"CUDA runtime API error 13: invalid device symbol"
