### ISSUE TITLE
Correct way to encode hg38 ?

### ISSUE THREAD

**Issue by karlkashofer** [RWilton/Arioc#20]
I try to encode the latest masked hg38 reference and face some problems. the file i want to encode is here: [GRCh38](https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/references/GRCh38/)
It contains maskings for some problems in the original hg38, see this [blogpost](https://genomeref.blogspot.com/2021/07/one-of-these-things-doest-belong.html)  and [paper.](https://www.biorxiv.org/content/10.1101/2021.06.07.444885v3.full)  

It has 195 contigs, using wildcard matching for the individual contigs like:

`    <file SN="*" subId="1">GCA_000001405.15_GRCh38_no_alt_analysis_set_maskedGRC_exclusions_v2.fasta</file>`

yields:

`worker@sx253:/scratch/karl/arioc/R/GRCh38_masked_v2$ ../../Arioc_150/bin/AriocE AriocE_HG38_p13.ungapped.cfg 
215111040 [0001217e] AriocE v1.50.3035.21246 (release) +2021-09-03T17:49:58
cat: /etc/system-release: No such file or directory
215111046 [0001217e] Copyright (c) 2015-2021 Johns Hopkins University.  All rights reserved.
215111046 [0001217e]  compiled             : 2021-09-24T16:15:04 (GNU g++ v8.3.0)
215111046 [0001217e]  data type sizes      : int=4 long=8 *=8 Jvalue5=5 Jvalue8=8 JtableHeader=5 (little-endian)
215111046 [0001217e]  computer name        : sx253
215111046 [0001217e]  executable file      : /scratch/karl/arioc/Arioc_150/bin/AriocE
215111046 [0001217e]  configuration file   : /scratch/karl/arioc/R/GRCh38_masked_v2/AriocE_HG38_p13.ungapped.cfg
215112579 [0001217e] AriocE::encodeR: encoding 1 file (32 CPU threads available)...
220200556 [00012183] ApplicationException ([0x00074115] AriocE/tuEncodeFASTA.cpp 64): Aggregated R sequence length 3099956958 exceeds the maximum supported length 1073741823: /scratch/karl/arioc/R/GRCh38_masked_v2/GCA_000001405.15_GRCh38_no_alt_analysis_set_maskedGRC_exclusions_v2.fasta
`

splitting the fasta into individual chromosomes and using one file line for each chromosome (n=195) of the reference yields:

`worker@sx253:/scratch/karl/arioc/R/GRCh38_masked_v2$ ../../Arioc_150/bin/AriocE AriocE_HG38_p13.gapped.cfg 
230517831 [000126de] AriocE v1.50.3035.21246 (release) +2021-09-03T17:49:58
cat: /etc/system-release: No such file or directory
230517838 [000126de] Copyright (c) 2015-2021 Johns Hopkins University.  All rights reserved.
230517838 [000126de]  compiled             : 2021-09-24T16:15:04 (GNU g++ v8.3.0)
230517838 [000126de]  data type sizes      : int=4 long=8 *=8 Jvalue5=5 Jvalue8=8 JtableHeader=5 (little-endian)
230517838 [000126de]  computer name        : sx253
230517838 [000126de]  executable file      : /scratch/karl/arioc/Arioc_150/bin/AriocE
230517838 [000126de]  configuration file   : /scratch/karl/arioc/R/GRCh38_masked_v2/AriocE_HG38_p13.gapped.cfg
230518180 [000126de] AriocE::encodeR: encoding 195 files (32 CPU threads available)...
230543830 [000126de] RaiiFile::internalOpen: Unable to open file: /scratch/karl/arioc/R/GRCh38_masked_v2/chromosomes/chrUn_KI270414v1.fa (error 24: Too many open files)
Segmentation fault
`

So, how do i correctly encode the hg38 reference with all its masking chromosomes ?

**Comment by RWilton** [comment]
Please encode each of the canonical GRCh38 chromosomes in its own FASTA file.  Place the 195 "masking chromosomes" into an additional FASTA file and reference it in the configuration file as well.  You will, of course, need to ensure that each of the 195 deflines in that FASTA file is formatted so that a unique identifier (in SAM/BAM, `SN` or "sequence name") for each can be parsed by using a simple wildcard specification.

Here is an example where the unique ID is the third bar-separated field in each defline:

 `<file SN="*|*|(*)|" subId="101" uriPath="https://rvdb.dbi.udel.edu/">U-RVDBv21.0.TP.1.fasta</file>`

The `subId=` parameter is required and must be unique in the configuration file.

If it will help, the Arioc documentation says a bit more about how to accomplish this.

As an aside:  5 or 6 months ago I was asked by my colleague, Steven Salzberg, to take a look at the Simons Genome Diversity Project coverage of those erroneously duplicated regions in GRCh38.  It wasn't trivial to sort out, because a short-read aligner simply sees multiple potential mappings for reads that originate in the problematic regions, and the mappings are distributed between those regions nondeterministically, i.e., they may be spread across both regions "randomly" or may tend to pile up in one of the two regions.  Either way, they have very low MAPQs because they have equivalent mappings in at least two different places.  It's similar to what can happen with "alt contigs"...

**Comment by karlkashofer** [comment]
I did use the wildcard defline approach in my first attempt which yielded the "Aggregated R sequence length 3099956958 exceeds the maximum supported length 1073741823" error.

However, doing individual file lines for the large canonical chromosomes, and packing the remaining 173 ones into one fasta referenced by wildcard matching has worked !

Thanks!

**Comment by karlkashofer** [comment]
OK, this story goes on. I now try to encode the official GATK hg38 reference from https://gatk.broadinstitute.org/hc/en-us/articles/360035890811-Resource-bundle

It contains >3500 contigs and apparently Arioc chokes on some of the deflines. As reported earlier i now use wildcard lines for encoding the reference, namely `<file SN="chr1" subId="1">chr1.fa</file>` for deflines of the canonical chromosomes:
`>chr1  AC:CM000663.2  gi:568336023  LN:248956422  rl:Chromosome  M5:6aef897c3d6ff0c78aff06ac189178dd  AS:GRCh38`
and wildcard matching
`<file SN="(*) *" subId="101">others.fa</file>`
for all other contigs concatenated into a single fasta file with deflines like
```
>chrUn_KN707992v1_decoy  AC:KN707992.1  gi:734691636  LN:1830  rl:unplaced  M5:1bac13a3ad2592a344e18bf8de117574  AS:hs38d1
...
>HLA-A*01:01:01:01      HLA00001 3503 bp
```

After encoding i use the reference for AriocP and it produces erroneous @SQ lines for the HLA chromosomes:
```
[E::sam_hrecs_error] Malformed key:value pair at line 2844: "@SQ	SN:HLA-A*01:01:01:01	HLA00001	LN:3503"
[E::sam_hrecs_error] Malformed key:value pair at line 2844: "@SQ	SN:HLA-A*01:01:01:01	HLA00001	LN:3503"
```

so it seems the "(*) *" parenthesis matching did not work for these deflines, it put two items into the SN tag of the HLA contigs which makes samtools choke.

Is this analysis correct ? Do you see a reason why the parenthesis matching did not work for the HLA contigs ?
Any recommendations on how to solve this ?

**Comment by RWilton** [comment]
Hello, Karl --

In the problematic definition line

`>HLA-A*01:01:01:01      HLA00001 3503 bp`

can you please confirm exactly which characters separate the strings `>HLA-A*01:01:01:01` and `HLA00001` in the FASTA input?  (You may need to do this with a binary editor or with a utility such as _hexdump_.)

**Comment by karlkashofer** [comment]
Dooh... they put a tab into these deflines....
Ill replace that tab by space and see...

**Comment by karlkashofer** [comment]
Yes, that solved it. Thanks for your help!

**Comment by karlkashofer** [comment]
Ok, used this reference for mapping a WGS file, seemed to work OK, even did GATK base quality recalibration on the resulting BAM. However, after that i want to use Manta to find structural variations, but it balks at the bam with:
`  Reference genome mismatch: Reference fasta file is missing a chromosome found in the Tumor BAM/CRAM file: '0.101#3341'
`
Looking into the header of the bam i do find a SQ line:
`@SQ	SN:0.101#3341	LN:129060516	UR:https://console.cloud.google.com/storage/browser/_details/genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.fasta/others.fa	rm:(multiple reference sequences)	`
This @SQ describes the file i put all the decoys in. The line is followed by @SQ lines for all the chromosomes in that file so that looks OK.
I tried to remove the superfluous  @SQ line from the bam with samtools reheader (just removing the one line) but then indexing the bam fails with:
`samtools index -@16 K274_16.bam 
samtools index: failed to create index for "K274_16.bam": Numerical result out of range
`
So, it seems currently i cant use this bam for Manta. I cant remove the @SQ line. 
Dont know what to do now.

**Comment by RWilton** [comment]
Hello Karl --

I am sorry you have run into a SAM/BAM formatting problem.  Let's see if we can figure out a workaround and maybe that will lead to a more definitive solution.

The first question pertains to the "superfluous" `@SQ` record in the SAM file.  Unfortunately, there is nothing explicit in the SAM/BAM format specification about the relationship between `@SQ-SN` (the sequence name tag in `@SQ`) and the `RNAME` field in alignment records.  Intuitively, you would assume that each `RNAME` must refer to a unique corresponding `@SQ-SN` (and in fact the spec points this out somewhere, sort of).

But the spec contains no inverse requirement, that is, there is no requirement for every `@SQ-SN` to correspond to at least one `RNAME`.  Such a requirement would be very hard on aligners as well as on tools that filter reads out of SAM/BAM files, since such tools would need to keep track of which `@SQ-SN` records were actually referenced by at least one `RNAME` in order to know which `@SQ` records to include in the output.

So, for an "aggregated" FASTA that contains multiple deflines, Arioc assumes that it's ok to write a `@SQ-SN` that provides metadata for the entire FASTA file.  (Where else could you possibly put that metadata, anyway?)  We know that this `@SQ`'s SN can never be referenced by an `RNAME` -- in fact, the `SN` string is just a placeholder -- so all is well, or should be.

Unfortunately, you now need to use a tool that seems to be unable to deal with such a SAM file.  So how do we handle this?

I could change Arioc so that it doesn't emit the `@SQ-SN` for the aggregated FASTA handle.  I suppose it could be turned into a `@CO` record or just omitted altogether.  I could do that next week if you want to wait.

Or you could spend five minutes creating a little FASTA file for SN:0.101#3341, containing nothing but a defline and some Ns.  (Who cares what's in it?  Nothing references it anyway.)  Hand that off to Manta and see if it's satisfied.

As for the worthless error message from _samtools index_:  what can I say?  You gave _samtools reheader_ a valid SAM/BAM file and it emitted something that _samtools index_ can't deal with.  I wouldn't spend more than a few minutes troubleshooting that, just to be sure that I hadn't made a parameterization error somewhere.  Then I would just pipe the original SAM/BAM file through _grep_ or maybe _sed_ to remove the line that contains "SN:0.101#3341".  I would double-check the resulting SAM output to be 100% sure that it looked right (i.e., just that one header line removed).  And I would then feed that to Manta and see what happens.

So let me know what you think, and how you'd like to approach this problem.  I'll try to help if I can, and as I said, I should be able to change Arioc to suppress that `@SQ` record in the next week or so.

· rw

**Comment by karlkashofer** [comment]
Hi Richard !
I removed the offending @SQ line (samtools view A274_16.bam | cat header.txt - | samtools view -b > A274_16.fixed.bam) which took a while, and Manta is finally happy with the bam file. Thus i would really appreciate if you could modify Arioc to suppress these @SQ lines.

**Comment by RWilton** [comment]
Done.

Please download build 3040, which supports an "extra" parameter named `suppressRaggSQ` that suppresses the output of the `@SQ` header record that contains only metadata for a FASTA file in which multiple reference sequences are aggregated.  To use this parameter, place it in the `<X>` element in the AriocU or AriocP configuration file:

`<X suppressRaggSQ="1" />`

The file _Xparams.txt_ in the Arioc distribution provides additional information.

If this approach doesn't work for you, please don't hesitate to open a new github issue!

**Comment by karlkashofer** [comment]
Hi Richard ! I tried using this parameter, it works and suppresses the @SQ line for the aggregated file. However, it seems to also suppress the @SQ lines for normal, no aggregated FASTA reference files leading to missing @SQ lines and SAM errors.
